### ISSUE TITLE
Jadx

### ISSUE THREAD

**Issue by 5E7EN** [mentebinaria/retoolkit#31]
Please consider adding Jadx (https://github.com/skylot/jadx) to the list of decompilers as well.

ref: https://twitter.com/ThatAndroidUser/status/1379244013308502017

**Comment by Rofliex** [comment]
Mb this will be better :)  -> https://github.com/Col-E/Recaf

**Comment by merces** [comment]
Cool. Added in [2021d](https://github.com/mentebinaria/retoolkit/releases/tag/2021d) release. Thanks!
