### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by HomeGrownCoder** [mentebinaria/retoolkit#35]
Looks like an .ico is missing 
![image](https://user-images.githubusercontent.com/11384057/122653745-c5062f00-d114-11eb-93f6-865136868ddc.png)

**Comment by merces** [comment]
Thanks for reporting. I'll make sure I add it to `asssets` folder soon. In the meantime, if you want to compile it, you can copy it from the program directory after installed. ;)

**Comment by HomeGrownCoder** [comment]
Thanks much

**Comment by merces** [comment]
Fixed by 79c6bdc4d45b7b191872dccfbb5bad072326b81f.
