### ISSUE TITLE
README.mdTranslation

### ISSUE THREAD

**Issue by cn-fairy** [mentebinaria/retoolkit#36]
Why?
    Because the current README.md is described in English, this translation was done to facilitate the replacement of non-English users to understand the tool set retoolkit. I hope it can be adopted and improved.
中文简体 (Chinese Simplified):
    Please see the uploaded attachment
[README_zh_CN.md](https://github.com/mentebinaria/retoolkit/files/6683749/README_zh_CN.md)

**Comment by cn-fairy** [comment]
Addendum：
The language switch option has not been added to Reademe because we don't know if this suggestion will be adopted.

Language Switching Case：
English:             Language : English| [中文简体(./README_zh_CN.md)
中文简体：       阅读语言选择：[English](./README.md) | 中文简体

**Comment by merces** [comment]
I appreciate that, @cn-fairy. Would you like to send a [pull request](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request)? Alternatively, I can download the file you sent and add it to the repository myself, and give you the credits on the commit message, but your name won't appear in [contributions](https://github.com/mentebinaria/retoolkit/graphs/contributors) this way. You tell me. :-)

Thanks!

**Comment by cn-fairy** [comment]
I pull a request so that it is easy to maintain later, and later there is a new version of the readme I directly translate and update.









--------------------------------------------------------------------------------





------------------ 原始邮件 ------------------




 
 发件人: "Fernando Mercês" ***@***.***>
 

 
 发送时间: 2021-06-21 21:47:34
 

 
 收件人:mentebinaria/retoolkit ***@***.***> 

 
 抄送:fairycn ***@***.***>,Mention ***@***.***> 

 
 主题: Re: [mentebinaria/retoolkit] README.mdTranslation (#36)
 





 I appreciate that, @cn-fairy. Would you like to send a pull request? Alternatively, I can download the file you sent and add it to the repository myself, and give you the credits on the commit message, but your name won't appear in contributions this way. You tell me. :-)

 Thanks!

**Comment by cn-fairy** [comment]
I pull a request so that it is easy to maintain later, and later there is a new version of the readme I directly translate and update.

**Comment by merces** [comment]
Hi @cn-fairy - are you still willing to send a pull request for this? README.md was updated by the way. :)

**Comment by cn-fairy** [comment]
New content has been updated and translated ：https://github.com/cn-fairy/retoolkit

**Comment by merces** [comment]
Nice! Can you open a pull request now? :)

**Comment by cn-fairy** [comment]
![image](https://user-images.githubusercontent.com/74580422/135544337-eecd2daf-259c-4655-8d36-12c82f31ba12.png)
GitHub is not used much, so I don't know if that's what it means

**Comment by merces** [comment]
You did great! Thank you very mcuh!
