### ISSUE TITLE
Add tools to context menu

### ISSUE THREAD

**Issue by merces** [mentebinaria/retoolkit#5]
I've been trying to add a few tools to the right-click menu on Windows but without success. It works for single entries, but I wanted to have them under a `retoolkit` sub-menu. The later only worked with admin rights. 😢

**Comment by ghost1372** [comment]
https://github.com/akinuri/custom-context-submenu

**Comment by lifenjoiner** [comment]
Try https://github.com/lifenjoiner/sendto-plus. It doesn't write registry! It just groups shortcuts by folders ;)

**Comment by merces** [comment]
Thanks a lot for the suggestions! I chose to go with SendTo+ as suggested by @lifenjoiner as recent versions of Windows limited the number of items in the sub-menu that you can create via registry.

**Comment by lifenjoiner** [comment]
I'm glad my tool can help anybody for a better life. Just follow the license. Especially, there are many software redistributed.

**Comment by merces** [comment]
Yup, it definitely helps! Thanks!

I read the licenses of the software included in the package and asked permission for those requiring it. Do you have any specific concern? Please, let me know. I take this very seriously.

Thanks,
Fernando

**Comment by lifenjoiner** [comment]
I tried the installer, and found that like some others there is only binary file of `sendto+`.
I think the license file should be included.
It would be better to include a `readme.md` file for anyone who wants to known the usage. Users may want to extend `retoolkit` with their existing tools, just by adding some shortcuts.

**Comment by merces** [comment]
Oh, you are right. Sorry about that. This was not by intent. I've opened #34 and will fix it for the next release. Does that sound ok for you?

Thanks again.

**Comment by lifenjoiner** [comment]
OK.
