### ISSUE TITLE
Bringing HyperDbg Debugger back to the RE Toolkit

### ISSUE THREAD

**Issue by SinaKarvandi** [mentebinaria/retoolkit#53]
Hi,
Thanks for your great work of gathering these amazing tools together!

Yesterday, we released the first version (v0.1) of the HyperDbg debugger along with its compiled binaries. It would be a pleasure to be in RE Toolkit again.

Thanks,

**Comment by merces** [comment]
These are fantastic news! It's our pleasure to include it. I'll keep it open until we release a new version containing HyperDbg. ❤️
