### ISSUE TITLE
Add FileInsight-plugins

### ISSUE THREAD

**Issue by WBGlIl** [mentebinaria/retoolkit#55]
FileInsight-plugins: decoding toolbox of McAfee FileInsight hex editor for malware analysis
https://github.com/nmantani/FileInsight-plugins

**Comment by merces** [comment]
Looks good, but I'd have to add the FileInsight editor too. I've checked its license but it is not clear about software redistribution. Just sent an e-mail to Trellix. Let's what they say. :)

Thanks for the suggestion!

**Comment by merces** [comment]
I got no answer from them, sorry.
