### ISSUE TITLE
Distribute the knowledge base (kb) files with IDR [Feature Request]

### ISSUE THREAD

**Issue by buzzer-re** [mentebinaria/retoolkit#78]
In order to [IDR](https://github.com/crypto2011/IDR) works we need the knowledge base (kb) files, the current folder contains the syskb*.bin files but it's missing the kb\<version\>.bin files, without them the analysis wont work. It can be found [here](https://drive.google.com/drive/folders/1IBsO1_O9xGHkPPV9Pnqkq2uoFmuak5C7)  inside the 7zip files.

**Comment by merces** [comment]
Fixed. Thanks.
