### ISSUE TITLE
Ajout de fonctionnalité : SynsinternalSuite

### ISSUE THREAD

**Issue by cjalouneix** [mentebinaria/retoolkit#82]
https://learn.microsoft.com/en-us/sysinternals/downloads/sysinternals-suite

**Comment by merces** [comment]
Thanks for your suggestion!

However, I don't think we need all of them, do we? Lots of them are meant to be used by sysadmins instead. For next release, I'm considering the following:

- Hex2dec
- Process Explorer
- Process Monitor
- Strings
- Sysinternal's TCPView

Thoughts? :)

**Comment by cjalouneix** [comment]
Hello and thank you for taking the time to reply.

I agree with you that you can't put everything in, and some of them are more in the sysadmin domain, but as part of a forensic analysis, I'll have a look at the ones you mention, as well as :

- Autoruns.exe
- Procmon.exe
- RDCMan.exe
- RAMMap.exe

another very interesting function, but only available in Windows PowerToys (https://github.com/microsoft/PowerToys), is the "File Locksmith" utility, which can be used to find current files and the processes "hooked" to them!

The ideal solution would perhaps be to create a dedicated Windows section with these tools, but I don't know if that's possible.
Congratulations again on a very useful product (sorry, I'm French, my English is very bad, so I prefer to use Google Translate :)). ).

Best regards,

**Comment by merces** [comment]
Hi @cjalouneix, thanks a lot for sharing your thoughts! I'll work to add them. :)

> Congratulations again on a very useful product

Thanks! The real hackers are the tools authors, but I must admit that putting them together requires a lot of work. :)

>  (sorry, I'm French, my English is very bad, so I prefer to use Google Translate :))

Oh, no reason to be sorry. I'm not a native speaker either and I appreciate your effort to share your thoughts here. 🙌

Au revoir 👋

**Comment by cjalouneix** [comment]
Thank's :)

**Comment by merces** [comment]
Ops, I was working on this while checked the license and we clearly can't add any Sysinternals tools. From their [FAQ](https://learn.microsoft.com/en-us/sysinternals/license-faq):

> **May I distribute Sysinternals utilities in my software, on my website, or with my magazine?**
No. We are not offering any distribution licenses, even if the 3rd party is distributing them for free. We encourage people to download the utilities from our download center where they can be assured to get the most recent version of the utility.

Sorry. 😒

**Comment by cjalouneix** [comment]
Too bad, I thought the compatible license, so maybe for another product, in any case thank you,

bye !
