### ISSUE TITLE
Add 4n4lDetector

### ISSUE THREAD

**Issue by mxngel** [mentebinaria/retoolkit#83]
4n4lDetector is an analysis tool for Microsoft Windows executable files, libraries, drivers and mdumps for x86 and x64. As of v1.8 an extended use for analyzing anomalies in Linux ELF executables was also included. Its main objective is to collect the necessary information to facilitate the identification of malicious code inside the analyzed files. This tool analyzes, among other things, the PE header and its structure, the content of the sections, the different types of strings, among many other things. It also incorporates a multitude of its own ideas to recognize anomalies in the construction of files and the detection of mechanisms used by current malware.

https://www.enelpc.com/p/4n4ldetector.html
https://github.com/4n0nym0us/4n4lDetector

**Comment by merces** [comment]
Great work. Thanks! It'll be in the next release coming soon.

**Comment by ExeinfoASL** [comment]
I tested this tool , but no strong power for me.

**Comment by merces** [comment]
> I tested this tool , but no strong power for me.

Well, I understand there are many tools that detect anomalies in binaries out there, but one more doesn't hurt, especially if the authors keep improving them and, most importantly, adding useful features and hacky detection rules. So, I thought it'd be a good idea to support the authors here. 😊
