### ISSUE TITLE
unable to Update windows 

### ISSUE THREAD

**Issue by 3ud4jm0nj4** [mentebinaria/retoolkit#90]
hello, i used retoolkit, and checked in box Disables Window Update, after that i cant install app in MS Store with error 0x80004002, how can i fix it, and i want Update windows too, i reinstall and uncheck that but not work. Thanks

**Comment by merces** [comment]
Thanks for reporting this. Here I got error code 0x80070422 instead. Anyway, try this:

1. Install retoolkit again. Make sure "Disable Windows Updates" checkbox is **checked**.
2. Open `C:\Users\admin\AppData\Local\Programs\retoolkit\utilities\wub` folder, or adjust if you changed the default installation folder.
3. Run `Wub_x64.exe`, select "Enable Updates". Click "Apply Now".
4. Try installing your apps again.

Let me know how it goes. :)

**Comment by 3ud4jm0nj4** [comment]
Thanks for your help, it worked

**Comment by merces** [comment]
I'm reopening it just to remind me I should do something about it in the next release. Ideas include:

* Warn the user this is going to happen.
* Add Windows Update Blocker to [Utilities](https://github.com/mentebinaria/retoolkit/wiki/Utilities) with a proper shortcut.
* Re-enable Windows Updates if retoolkit is uninstalled.

**Comment by merces** [comment]
Closed by [126c8b ](https://github.com/mentebinaria/retoolkit/commit/36dcd1e750a09210f9c45eff6bf66c09b2322b2c) and https://github.com/mentebinaria/retoolkit/commit/126c8b18826669e6fc30defd083c3134b820dfe1.
